#include "app_control.h"
#include "board_config.h"
#include <string.h>
SensorData g_sensor;ThresholdConfig g_thresholds;OutputState g_auto_outputs,g_outputs;OverrideState g_overrides;UiPage g_ui_page;
static int16_t ci(int32_t v,int16_t l,int16_t h){if(v<l)return l;if(v>h)return h;return(int16_t)v;}static uint16_t cu(int32_t v,uint16_t l,uint16_t h){if(v<(int32_t)l)return l;if(v>(int32_t)h)return h;return(uint16_t)v;}
static bool expired(uint32_t now,uint32_t until){return (int32_t)(now-until)>=0;}
static bool resolve(bool automatic,OutputMode mode){if(mode==OUTPUT_FORCE_ON)return true;if(mode==OUTPUT_FORCE_OFF)return false;return automatic;}
void app_all_auto(void){g_overrides.pump=g_overrides.fan=g_overrides.light=g_overrides.buzzer=OUTPUT_AUTO;g_overrides.pump_until=g_overrides.fan_until=g_overrides.light_until=g_overrides.buzzer_until=0;}
void app_init(void){g_sensor.temperature=25;g_sensor.humidity=55;g_sensor.air_quality=300;g_sensor.light=500;g_sensor.soil=500;g_sensor.valid=0;g_thresholds.temp_min=DEFAULT_TEMP_MIN;g_thresholds.temp_max=DEFAULT_TEMP_MAX;g_thresholds.humi_min=DEFAULT_HUMI_MIN;g_thresholds.humi_max=DEFAULT_HUMI_MAX;g_thresholds.air_max=DEFAULT_AIR_MAX;g_thresholds.light_min=DEFAULT_LIGHT_MIN;g_thresholds.soil_min=DEFAULT_SOIL_MIN;g_ui_page=UI_VALUES;app_all_auto();app_evaluate();}
void app_evaluate(void){bool d=(g_sensor.valid&1U)!=0,a=(g_sensor.valid&2U)!=0;g_auto_outputs.led1=d&&g_sensor.temperature>g_thresholds.temp_max;g_auto_outputs.led2=d&&g_sensor.temperature<g_thresholds.temp_min;g_auto_outputs.led3=d&&g_sensor.humidity>g_thresholds.humi_max;g_auto_outputs.led4=d&&g_sensor.humidity<g_thresholds.humi_min;g_auto_outputs.pump=a&&g_sensor.soil<g_thresholds.soil_min;g_auto_outputs.fan=a&&g_sensor.air_quality>g_thresholds.air_max;g_auto_outputs.light=a&&g_sensor.light<g_thresholds.light_min;g_auto_outputs.buzzer=g_auto_outputs.fan;g_outputs=g_auto_outputs;g_outputs.pump=resolve(g_auto_outputs.pump,g_overrides.pump);g_outputs.fan=resolve(g_auto_outputs.fan,g_overrides.fan);g_outputs.light=resolve(g_auto_outputs.light,g_overrides.light);g_outputs.buzzer=resolve(g_auto_outputs.buzzer,g_overrides.buzzer);}
void app_service_overrides(uint32_t n){if(g_overrides.pump!=OUTPUT_AUTO&&expired(n,g_overrides.pump_until))g_overrides.pump=OUTPUT_AUTO;if(g_overrides.fan!=OUTPUT_AUTO&&expired(n,g_overrides.fan_until))g_overrides.fan=OUTPUT_AUTO;if(g_overrides.light!=OUTPUT_AUTO&&expired(n,g_overrides.light_until))g_overrides.light=OUTPUT_AUTO;if(g_overrides.buzzer!=OUTPUT_AUTO&&expired(n,g_overrides.buzzer_until))g_overrides.buzzer=OUTPUT_AUTO;app_evaluate();}
bool app_set_thresholds(const ThresholdConfig*c){if(c->temp_min<-20||c->temp_max>80||c->temp_min>c->temp_max||c->humi_min>100||c->humi_max>100||c->humi_min>c->humi_max||c->air_max>1023||c->light_min>1023||c->soil_min>1023)return false;g_thresholds=*c;app_evaluate();return true;}
bool app_set_override(const char*n,OutputMode m,uint16_t ttl,uint32_t now){OutputMode*p;uint32_t*u;uint16_t max;if(!strcmp(n,"PUMP")){p=&g_overrides.pump;u=&g_overrides.pump_until;max=120;}else if(!strcmp(n,"FAN")){p=&g_overrides.fan;u=&g_overrides.fan_until;max=1800;}else if(!strcmp(n,"LAMP")){p=&g_overrides.light;u=&g_overrides.light_until;max=1800;}else if(!strcmp(n,"BEEP")){p=&g_overrides.buzzer;u=&g_overrides.buzzer_until;max=60;}else return false;if(m!=OUTPUT_AUTO&&(ttl==0||ttl>max))return false;*p=m;*u=m==OUTPUT_AUTO?0:now+(uint32_t)ttl*1000U;app_evaluate();return true;}
uint16_t app_override_remaining(OutputMode m,uint32_t u,uint32_t n){uint32_t r;if(m==OUTPUT_AUTO||expired(n,u))return 0;r=u-n;return(uint16_t)((r+999U)/1000U);}
bool app_editing(void){return g_ui_page>=UI_TEMP_MIN;}void app_next_page(void){if(app_editing())g_ui_page=UI_VALUES;else g_ui_page=g_ui_page==UI_VALUES?UI_THRESHOLDS:UI_VALUES;}void app_next_field(void){if(!app_editing())g_ui_page=UI_TEMP_MIN;else g_ui_page=g_ui_page==UI_SOIL_MIN?UI_TEMP_MIN:(UiPage)(g_ui_page+1);}
void app_adjust(int8_t d){ThresholdConfig c=g_thresholds;switch(g_ui_page){case UI_TEMP_MIN:c.temp_min=ci(c.temp_min+d,-20,c.temp_max);break;case UI_TEMP_MAX:c.temp_max=ci(c.temp_max+d,c.temp_min,80);break;case UI_HUMI_MIN:c.humi_min=(uint8_t)cu((int32_t)c.humi_min+d,0,c.humi_max);break;case UI_HUMI_MAX:c.humi_max=(uint8_t)cu((int32_t)c.humi_max+d,c.humi_min,100);break;case UI_AIR_MAX:c.air_max=cu((int32_t)c.air_max+d*10,0,1023);break;case UI_LIGHT_MIN:c.light_min=cu((int32_t)c.light_min+d*10,0,1023);break;case UI_SOIL_MIN:c.soil_min=cu((int32_t)c.soil_min+d*10,0,1023);break;default:break;}app_set_thresholds(&c);}
