#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H
#include "stm32f10x.h"
#include "common.h"

#define APP_UART_BAUD 19200U
#define OLED_ADDRESS 0x3CU
#define DEFAULT_TEMP_MIN 18
#define DEFAULT_TEMP_MAX 32
#define DEFAULT_HUMI_MIN 40
#define DEFAULT_HUMI_MAX 80
#define DEFAULT_AIR_MAX 600
#define DEFAULT_LIGHT_MIN 300
#define DEFAULT_SOIL_MIN 350
#define KEY_PERIOD_MS 20U
#define ADC_PERIOD_MS 500U
#define DISPLAY_PERIOD_MS 250U
#define DHT_PERIOD_MS 2000U
#define SERIAL_PERIOD_MS 2000U

#define DHT_PORT GPIOA
#define DHT_PIN 0U
#define LED1_PORT GPIOA
#define LED1_PIN 15U
#define LED2_PORT GPIOC
#define LED2_PIN 13U
#define LED3_PORT GPIOC
#define LED3_PIN 14U
#define LED4_PORT GPIOC
#define LED4_PIN 15U
#define LIGHT_PORT GPIOB
#define LIGHT_PIN 0U
#define PUMP_PORT GPIOB
#define PUMP_PIN 12U
#define FAN_PORT GPIOB
#define FAN_PIN 14U
#define BUZZER_PORT GPIOA
#define BUZZER_PIN 12U
#define TIM3_CONFIGURED
#define KEY1_PORT GPIOB

#define KEY1_PIN 7U
#define KEY2_PORT GPIOB
#define KEY2_PIN 6U
#define SOIL_DIGITAL_PORT GPIOB
#define SOIL_DIGITAL_PIN 3U
#define APP_UART_PERIPH USART1
#define APP_UART_APB_MASK RCC_APB2ENR_USART1EN
#define APP_UART_PORT GPIOA
#define APP_UART_TX_PIN 9U
#define APP_UART_RX_PIN 10U
#define APP_UART_IRQn USART1_IRQn
#endif
